[dev]
command = "npm run dev"

[build]
command = "npm run build"
publish = "out"

[[headers]]
for = "/*.pdf"
values = { Cache-Control = "no-store" }

[[headers]]
for = "/models/*"
values = { Cache-Control = "public,max-age=365000000,immutable" }
