[dev]
	command = "bun dev"

[build]
	command = "bun run build"
	[build.environment]
		NEXT_USE_NETLIFY_EDGE = "true"

[[headers]]
	for = "/models/*"
	values = { Cache-Control = "public,max-age=365000000,immutable" }
