[build]
base = ''
command = 'npm run build'
publish = 'build'

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*.pdf"
values = { Cache-Control = "no-store" }

[build.environment]
SKIP_PREFLIGHT_CHECK = "true"
